### PR TITLE
Lower some masses to bring more inline with stock

### PR DESCRIPTION
**Pull request by theRagingIrishman**

### CODE REVIEW

**Comment by tjdeckard** [comment]
Don't we want the Konstruction bits to be on the heavier side to offset the weight of the things we're moving around or do we rely solely on the counterweight for that?

**Comment by theRagingIrishman** [comment]
@tjdeckard I changed the mass of the trusses and cradles because they were 2 to 3 times heavier than the equivalent structure in stock. I didn't touch the counterweight's mass

**Comment by tjdeckard** [comment]
It's probably a good idea to make the cradles on the lighter side (makes them more KAS-friendly) but I don't think it's necessarily a bad thing for the truss bits to be heavy just to add some more weight to the vehicle (in addition to the counterweight). But maybe the counterweights are enough. Making the truss segments KAS-friendly as well isn't necessarily a bad thing. You can always add more counterweights!

**Comment by theRagingIrishman** [comment]
Ya my thought was that it's always easy to add more mass to a ship but it's impossible to remove mass

**Comment by tjdeckard** [comment]
I think what caught my attention was the title of the PR, "to bring more inline with stock". So I was like wait, is it more important for it to be inline with stock or true to the spirit of the mod?

**Pull request merged**
